version: '3.0'
services:

  billing:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:10.6-alpine
    restart: always
    container_name: "billing-postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=billing
    ports:
      - 5432:5432
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"