version: '3.0'
services:

  billing:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:10.6-alpine
    restart: always
    container_name: "billing-postgres"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - .docker-data/db/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh